apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  selector:
    matchLabels:
      app: back
  replicas: 2
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: neozero98/ecomerce-cdt-1
          ports:
            - containerPort: 80